"""Add deleted field on account

Revision ID: 3c740adbb4d1
Revises: 4300252b293e
Create Date: 2014-01-13 10:24:08.393667

"""

# revision identifiers, used by Alembic.
revision = '3c740adbb4d1'
down_revision = '4300252b293e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'deleted')
    ### end Alembic commands ###
