"""Encas database

Revision ID: 40e6a7b1fc07
Revises: None
Create Date: 2014-01-20 17:31:20.473294

"""

# revision identifiers, used by Alembic.
revision = '40e6a7b1fc07'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation', sa.DateTime(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=False),
    sa.Column('lastname', sa.String(length=64), nullable=False),
    sa.Column('promo', sa.String(length=64), nullable=True),
    sa.Column('staff', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('operation', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revokes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['revokes'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('accounts')
    op.drop_table('users')
    ### end Alembic commands ###
