"""Ajout du champ revokes

Revision ID: 4fe14b0c6dd0
Revises: 3c740adbb4d1
Create Date: 2014-01-13 16:22:28.459948

"""

# revision identifiers, used by Alembic.
revision = '4fe14b0c6dd0'
down_revision = '3c740adbb4d1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('revokes', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'revokes')
    ### end Alembic commands ###
